# Generated by Django 5.2.2 on 2026-10-01 20:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='Count', max_length=50)),
                ('target_type', models.CharField(choices=[('NUMBER', 'Number'), ('PERCENTAGE', 'Percentage'), ('TIME', 'Time')], default='NUMBER', max_length=20)),
                ('default_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='performance_is_acti_7406f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='employees.employeeprofile')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_targets', to='performance.kpi')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['employee', 'kpi'], name='performance_employe_e479ab_idx'), models.Index(fields=['effective_from'], name='performance_effecti_2e047f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='employees.employeeprofile')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_records', to='performance.kpi')),
            ],
            options={
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='performance_employe_52e283_idx'), models.Index(fields=['date'], name='performance_date_fc834a_idx'), models.Index(fields=['kpi'], name='performance_kpi_id_af25d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'kpi', 'date'), name='uniq_performance_per_emp_kpi_date')],
            },
        ),
    ]
