# Generated by Django 5.2.2 on 2026-10-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'Leave'), ('HOLIDAY', 'Holiday'), ('WEEK_OFF', 'Week Off')], default='PRESENT', max_length=20)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'), models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_attendance_per_emp_date')],
            },
        ),
    ]
