# Generated by Django 5.2.2 on 2026-10-01 15:34

import apps.employees.models
import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('date_of_joining', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[common.validators.validate_phone])),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[common.validators.validate_phone])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=apps.employees.models.profile_image_path)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_NOTICE', 'On Notice'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.department')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.process')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.team')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_code'],
                'indexes': [models.Index(fields=['department'], name='employees_e_departm_a4f430_idx'), models.Index(fields=['process'], name='employees_e_process_cfbced_idx'), models.Index(fields=['team'], name='employees_e_team_id_4f4836_idx'), models.Index(fields=['status'], name='employees_e_status_3a8215_idx'), models.Index(fields=['created_at'], name='employees_e_created_5afbcd_idx')],
            },
        ),
    ]
